version: 2.1

workflows:
  lint:
    jobs:
      - lint
  build:
    jobs:
      - test
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

jobs:
  lint:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: 
          name: Install staticcheck
          command: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run:
          name: Run staticcheck
          command: staticcheck ./...

  test:
    docker:
      - image: circleci/golang:1.16
      - image: andyzhouty/flog:latest
    environment:
      TEST_RESULTS: /tmp/test-reports
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          paths:
            - "/go/pkg/mod"
          key: go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Wait for flog server to be ready
          command: dockerize -wait http://localhost:5000 -timeout 30s
      - run:
          name: Run unit tests
          environment:
            TESTING: "true"
            FLOG_USERNAME: "flog_admin"
            FLOG_PASSWORD: "flog_admin_password"
          command:
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

  release:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
